<?php
/**
 * @file   api_gen.php
 * @brief  Generate REST API endpoint code from table schema.
 */
require_once __DIR__ . '/includes/session.php';
requireLogin();

$dbName = $_SESSION['db_name'] ?? '';
$dbType = $_SESSION['db_type'] ?? 'mysql';
$db = getDbConnection();
$tables = $db ? $db->getAllTables($dbName) : [];

$selectedTable = $_POST['table'] ?? $_GET['table'] ?? '';
$namespace     = $_POST['namespace'] ?? 'App\\Api';
$authType      = $_POST['auth_type'] ?? 'bearer';
$generatedCode = '';

if ($selectedTable && $db) {
    try {
        $schema = $db->getTableSchema($selectedTable, $dbName);
        $pk     = $db->getPrimaryKey($selectedTable, $dbName);
        $pkCol  = $pk[0] ?? 'id';

        // Build column list for validation/insert/update
        $columns = [];
        $fillable = [];
        foreach ($schema as $col) {
            $columns[] = $col;
            // Skip auto-increment / serial primary keys for fillable
            $extra = strtolower($col['extra'] ?? '');
            if (in_array($col['name'], $pk) && (str_contains($extra, 'auto_increment') || str_contains($extra, 'serial'))) {
                continue;
            }
            $fillable[] = $col;
        }

        // Generate the API code
        $tableSafe   = addslashes($selectedTable);
        $pkSafe      = addslashes($pkCol);
        $dbNameSafe  = addslashes($dbName);
        $classDbType = addslashes($dbType);

        $validationRules = [];
        foreach ($fillable as $col) {
            $rule = "'" . addslashes($col['name']) . "' => [";
            $parts = [];
            if (!$col['nullable'] && ($col['default'] ?? '') === '') {
                $parts[] = "'required'";
            }
            $type = strtolower($col['type']);
            if (preg_match('/int|serial/i', $type))           $parts[] = "'integer'";
            elseif (preg_match('/float|double|decimal|numeric/i', $type)) $parts[] = "'numeric'";
            elseif (preg_match('/bool/i', $type))              $parts[] = "'boolean'";
            else                                                $parts[] = "'string'";
            $rule .= implode(', ', $parts) . ']';
            $validationRules[] = $rule;
        }
        $rulesStr = implode(",\n            ", $validationRules);

        $fillableNames = array_map(fn($c) => "'" . addslashes($c['name']) . "'", $fillable);
        $fillableStr   = implode(', ', $fillableNames);

        $authBlock = '';
        if ($authType === 'bearer') {
            $authBlock = <<<'AUTH'

// --- Authentication (Bearer Token) ---
$headers = getallheaders();
$token   = '';
if (isset($headers['Authorization'])) {
    if (preg_match('/^Bearer\s+(.+)$/i', $headers['Authorization'], $m)) {
        $token = $m[1];
    }
}
if ($token !== API_TOKEN) {
    http_response_code(401);
    echo json_encode(['error' => 'Unauthorized']);
    exit;
}
AUTH;
        } elseif ($authType === 'apikey') {
            $authBlock = <<<'AUTH'

// --- Authentication (API Key) ---
$apiKey = $_SERVER['HTTP_X_API_KEY'] ?? $_GET['api_key'] ?? '';
if ($apiKey !== API_TOKEN) {
    http_response_code(401);
    echo json_encode(['error' => 'Unauthorized']);
    exit;
}
AUTH;
        }

        $generatedCode = <<<PHP
<?php
/**
 * REST API Endpoint for "{$tableSafe}" table.
 *
 * Supports: GET (list + single), POST (create), PUT (update), DELETE.
 * Generated by DBExplorer-2 API Generator.
 */

header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, Authorization, X-API-Key');

// Handle preflight
if (\$_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(204);
    exit;
}

// --- Configuration ---
define('API_TOKEN', 'CHANGE_ME_TO_A_SECURE_TOKEN');

// Database connection settings
\$dbConfig = [
    'type'     => '{$classDbType}',
    'host'     => '{$_SESSION['db_host']}',
    'port'     => {$_SESSION['db_port']},
    'username' => '', // Set your DB credentials
    'password' => '', // Set your DB credentials
    'database' => '{$dbNameSafe}',
];
{$authBlock}

// --- Database Connection ---
require_once __DIR__ . '/classes/DatabaseFactory.php';

try {
    \$db = DatabaseFactory::create(
        \$dbConfig['type'],
        \$dbConfig['host'],
        \$dbConfig['username'],
        \$dbConfig['password'],
        \$dbConfig['database'],
        \$dbConfig['port']
    );
} catch (\\Exception \$e) {
    http_response_code(500);
    echo json_encode(['error' => 'Database connection failed']);
    exit;
}

// --- Helpers ---
\$table    = '{$tableSafe}';
\$database = '{$dbNameSafe}';
\$pkColumn = '{$pkSafe}';
\$fillable = [{$fillableStr}];

\$validationRules = [
    {$rulesStr}
];

function validateInput(array \$data, array \$rules, bool \$partial = false): array {
    \$errors = [];
    foreach (\$rules as \$field => \$fieldRules) {
        \$value = \$data[\$field] ?? null;
        if (in_array('required', \$fieldRules) && !\\$partial && (\$value === null || \$value === '')) {
            \$errors[] = "Field '{\$field}' is required.";
            continue;
        }
        if (\$value === null || \$value === '') continue;
        if (in_array('integer', \$fieldRules) && !is_numeric(\$value)) {
            \$errors[] = "Field '{\$field}' must be an integer.";
        }
        if (in_array('numeric', \$fieldRules) && !is_numeric(\$value)) {
            \$errors[] = "Field '{\$field}' must be numeric.";
        }
        if (in_array('boolean', \$fieldRules) && !in_array(\$value, [0, 1, '0', '1', true, false], true)) {
            \$errors[] = "Field '{\$field}' must be boolean.";
        }
    }
    return \$errors;
}

function jsonResponse(mixed \$data, int \$code = 200): void {
    http_response_code(\$code);
    echo json_encode(\$data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
    exit;
}

// --- Routing ---
\$method = \$_SERVER['REQUEST_METHOD'];
\$id     = \$_GET['id'] ?? null;
\$page   = max(1, (int)(\$_GET['page'] ?? 1));
\$limit  = min(500, max(1, (int)(\$_GET['limit'] ?? 50)));
\$offset = (\$page - 1) * \$limit;

try {
    switch (\$method) {

        // ==================== GET ====================
        case 'GET':
            if (\$id !== null) {
                // Single record
                \$found = null;
                foreach (\$db->getTableData(\$table, \$database, 1, 0) as \$row) {
                    // We need to search by PK — use rawQuery instead
                }
                \$sql = "SELECT * FROM {\$table} WHERE {\$pkColumn} = ?";
                foreach (\$db->rawQuery(\$sql, [\$id]) as \$row) {
                    \$found = \$row;
                    break;
                }
                if (!\$found) jsonResponse(['error' => 'Not found'], 404);
                jsonResponse(['data' => \$found]);
            } else {
                // List with pagination
                \$rows  = [];
                \$total = \$db->countRows(\$table, \$database);
                foreach (\$db->getTableData(\$table, \$database, \$limit, \$offset) as \$row) {
                    \$rows[] = \$row;
                }
                jsonResponse([
                    'data'       => \$rows,
                    'pagination' => [
                        'page'       => \$page,
                        'limit'      => \$limit,
                        'total'      => \$total,
                        'totalPages' => (int)ceil(\$total / \$limit),
                    ],
                ]);
            }
            break;

        // ==================== POST (Create) ====================
        case 'POST':
            \$input = json_decode(file_get_contents('php://input'), true) ?? [];
            \$data  = array_intersect_key(\$input, array_flip(\$fillable));
            \$errors = validateInput(\$data, \$validationRules, false);
            if (\$errors) jsonResponse(['errors' => \$errors], 422);
            \$newId = \$db->insert(\$table, \$data, \$database);
            jsonResponse(['message' => 'Created', 'id' => \$newId], 201);
            break;

        // ==================== PUT (Update) ====================
        case 'PUT':
            if (\$id === null) jsonResponse(['error' => 'ID required for update'], 400);
            \$input = json_decode(file_get_contents('php://input'), true) ?? [];
            \$data  = array_intersect_key(\$input, array_flip(\$fillable));
            if (empty(\$data)) jsonResponse(['error' => 'No valid fields to update'], 400);
            \$errors = validateInput(\$data, \$validationRules, true);
            if (\$errors) jsonResponse(['errors' => \$errors], 422);
            \$affected = \$db->update(\$table, \$data, [\$pkColumn => \$id], \$database);
            jsonResponse(['message' => 'Updated', 'affected' => \$affected]);
            break;

        // ==================== DELETE ====================
        case 'DELETE':
            if (\$id === null) jsonResponse(['error' => 'ID required for delete'], 400);
            \$affected = \$db->delete(\$table, [\$pkColumn => \$id], \$database);
            if (\$affected === 0) jsonResponse(['error' => 'Not found'], 404);
            jsonResponse(['message' => 'Deleted', 'affected' => \$affected]);
            break;

        default:
            jsonResponse(['error' => 'Method not allowed'], 405);
    }
} catch (\\Exception \$e) {
    jsonResponse(['error' => \$e->getMessage()], 500);
} finally {
    \$db->disconnect();
}
PHP;

    } catch (\Exception $e) {
        setFlash('error', $e->getMessage());
    }
}

if ($db) $db->disconnect();

$pageTitle = 'API Generator';
require_once __DIR__ . '/includes/header.php';
?>

<div class="breadcrumb">
    <a href="databases.php">Databases</a><span>&rsaquo;</span>
    <a href="tables.php"><?= e(displayDbName()) ?></a><span>&rsaquo;</span>
    <strong>API Generator</strong>
</div>

<div class="card">
    <h2 class="card-title">Generate REST API Endpoint</h2>
    <p class="text-muted mb-2">Select a table to generate a standalone REST API PHP file with GET, POST, PUT, and DELETE support.</p>

    <form method="post" class="flex gap-2 flex-wrap items-center mb-2">
        <div class="form-group form-group-flex">
            <label>Table</label>
            <select name="table" required>
                <option value="">-- Select Table --</option>
                <?php foreach ($tables as $t): ?>
                    <option value="<?= e($t) ?>" <?= $selectedTable===$t?'selected':'' ?>><?= e($t) ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group form-group-fixed-md">
            <label>Namespace</label>
            <input type="text" name="namespace" value="<?= e($namespace) ?>" placeholder="App\Api">
        </div>
        <div class="form-group form-group-fixed">
            <label>Auth Type</label>
            <select name="auth_type">
                <option value="bearer" <?= $authType==='bearer'?'selected':'' ?>>Bearer Token</option>
                <option value="apikey" <?= $authType==='apikey'?'selected':'' ?>>API Key Header</option>
                <option value="none"   <?= $authType==='none'?'selected':'' ?>>None</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary btn-form-aligned">Generate</button>
    </form>
</div>

<?php if ($generatedCode): ?>
<div class="card">
    <h2 class="card-title">
        Generated API: <?= e($selectedTable) ?>
        <span class="title-actions">
            <button class="btn btn-sm btn-secondary copy-btn" data-action="copyCode">Copy Code</button>
        </span>
    </h2>
    <p class="text-muted mb-2">
        <strong>Usage:</strong> Save as <code>api_<?= e($selectedTable) ?>.php</code>.
        Call with <code>GET /api_<?= e($selectedTable) ?>.php?page=1&amp;limit=50</code>,
        <code>GET ?id=123</code>, <code>POST</code> JSON body, <code>PUT ?id=123</code>, <code>DELETE ?id=123</code>.
    </p>
    <div class="code-wrap">
        <pre class="code-block" id="generatedCode"><?= e($generatedCode) ?></pre>
    </div>
</div>
<?php endif; ?>

<?php require_once __DIR__ . '/includes/footer.php'; ?>
