services:
  dbexplorer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbexplorer-app
    ports:
      - "${DBEXPLORER_PORT:-8082}:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
