<?php
/**
 * @file   documenter_pdf.php
 * @brief  Export schema documentation as a PDF report.
 */
require_once __DIR__ . '/includes/session.php';
requireLogin();
require_once __DIR__ . '/classes/fpdf.php';

$dbName  = $_SESSION['db_name'] ?? '';
$dbType  = DatabaseFactory::DRIVERS[$_SESSION['db_type']] ?? $_SESSION['db_type'];
$dbLabel = displayDbName();

$db     = getDbConnection();
$tables = $db ? $db->getAllTables($dbName) : [];
$allSchema = [];

if ($db) {
    foreach ($tables as $t) {
        try {
            $schema = $db->getTableSchema($t, $dbName);
            $pk     = $db->getPrimaryKey($t, $dbName);
            $count  = $db->countRows($t, $dbName);
            $allSchema[] = [
                'name'   => $t,
                'schema' => $schema,
                'pk'     => $pk,
                'rows'   => $count,
            ];
        } catch (\Exception $e) {
            $allSchema[] = [
                'name'   => $t,
                'schema' => [],
                'pk'     => [],
                'rows'   => 0,
                'error'  => $e->getMessage(),
            ];
        }
    }
    $db->disconnect();
}

/* ================================================================
   Custom PDF class with header / footer
   ================================================================ */

class SchemaPDF extends FPDF
{
    public string $reportTitle = 'Schema Documentation';
    public string $dbLabel     = '';
    public string $dbType      = '';

    /**
     * @brief Render the document header.
     */
    function Header(): void
    {
        // Blue header bar
        $this->SetFillColor(27, 58, 92);   // --bg-header #1B3A5C
        $this->Rect(0, 0, $this->GetPageWidth(), 18, 'F');

        $this->SetFont('Helvetica', 'B', 11);
        $this->SetTextColor(255, 255, 255);
        $this->SetXY(10, 4);
        $this->Cell(0, 10, $this->encText($this->reportTitle), 0, 0, 'L');

        // Right side: db name + type
        $this->SetFont('Helvetica', '', 8);
        $this->SetXY(-80, 4);
        $this->Cell(70, 10, $this->encText($this->dbType . ' | ' . $this->dbLabel), 0, 0, 'R');

        $this->Ln(16);
    }

    /**
     * @brief Render the document footer.
     */
    function Footer(): void
    {
        $this->SetY(-12);
        $this->SetFont('Helvetica', 'I', 7);
        $this->SetTextColor(120, 120, 120);
        $this->Cell(0, 10, 'Generated by DBExplorer-2 (David S. Harmor)  |  Page ' . $this->PageNo() . '/{nb}', 0, 0, 'C');
    }

    /**
     * Safe Latin-1 encode for FPDF (which doesn't support UTF-8 natively).
     */
    function encText(?string $text): string
    {
        if ($text === null || $text === '') return '';
        $encoded = @iconv('UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $text);
        return $encoded !== false ? $encoded : $text;
    }

    /**
     * Render a section heading.
     */
    function SectionHeading(string $label): void
    {
        $this->SetFont('Helvetica', 'B', 12);
        $this->SetTextColor(27, 58, 92);
        $this->Cell(0, 8, $this->encText($label), 0, 1, 'L');
        $this->SetDrawColor(43, 108, 176);
        $this->Line($this->GetX(), $this->GetY(), $this->GetX() + $this->GetPageWidth() - 20, $this->GetY());
        $this->Ln(2);
    }

    /**
     * Render a table heading row.
     */
    function TableHeader(array $cols, array $widths): void
    {
        $this->SetFont('Helvetica', 'B', 7.5);
        $this->SetFillColor(43, 108, 176);  // --accent-primary
        $this->SetTextColor(255, 255, 255);
        for ($i = 0; $i < count($cols); $i++) {
            $this->Cell($widths[$i], 6, $this->encText($cols[$i]), 1, 0, 'C', true);
        }
        $this->Ln();
        $this->SetTextColor(26, 32, 44);
    }

    /**
     * Render a table data row with alternating fill.
     */
    function TableRow(array $values, array $widths, bool $fill): void
    {
        $this->SetFont('Helvetica', '', 7);
        if ($fill) {
            $this->SetFillColor(244, 247, 251);  // --bg-card-alt
        }
        for ($i = 0; $i < count($values); $i++) {
            $align = ($i === 0) ? 'L' : 'L';
            $this->Cell($widths[$i], 5, $this->encText($values[$i]), 1, 0, $align, $fill);
        }
        $this->Ln();
    }

    /**
     * Check if we need a page break before a table section.
     */
    function NeedPageBreak(float $height): bool
    {
        return ($this->GetY() + $height > $this->GetPageHeight() - 20);
    }
}

/* ================================================================
   Build the PDF
   ================================================================ */

$pdf = new SchemaPDF('L', 'mm', 'Letter');  // Landscape Letter size
$pdf->reportTitle = 'Schema Documentation: ' . $dbLabel;
$pdf->dbLabel     = $dbLabel;
$pdf->dbType      = $dbType;
$pdf->AliasNbPages();
$pdf->SetAutoPageBreak(true, 18);
$pdf->SetMargins(10, 22, 10);
$pdf->AddPage();

// ── Title page info ──
$pdf->SetFont('Helvetica', 'B', 18);
$pdf->SetTextColor(27, 58, 92);
$pdf->Cell(0, 12, $pdf->encText('Schema Documentation'), 0, 1, 'C');

$pdf->SetFont('Helvetica', '', 11);
$pdf->SetTextColor(74, 85, 104);
$pdf->Cell(0, 7, $pdf->encText('Database: ' . $dbLabel), 0, 1, 'C');
$pdf->Cell(0, 7, $pdf->encText('Server: ' . $dbType), 0, 1, 'C');
$pdf->Cell(0, 7, $pdf->encText('Tables: ' . count($allSchema) . '  |  Generated: ' . date('Y-m-d H:i:s')), 0, 1, 'C');
$pdf->Ln(6);

// ── Summary table ──
$pdf->SectionHeading('Summary');
$sumCols   = ['#', 'Table', 'Rows', 'Columns', 'Primary Key'];
$sumWidths = [10, 70, 25, 25, 129];  // total 259

$pdf->TableHeader($sumCols, $sumWidths);
foreach ($allSchema as $i => $info) {
    $pkStr = !empty($info['pk']) ? implode(', ', $info['pk']) : '-';
    $pdf->TableRow(
        [($i + 1), $info['name'], number_format($info['rows']), (string)count($info['schema']), $pkStr],
        $sumWidths,
        ($i % 2 === 1)
    );
}
$pdf->Ln(6);

// ── Detail for each table ──
$colHeaders = ['Column', 'Type', 'Nullable', 'Key', 'Default', 'Extra'];
$colWidths  = [50, 45, 20, 18, 63, 63];  // total 259

foreach ($allSchema as $info) {
    // Estimate height: heading (14) + header row (6) + data rows (5 each) + margin (8)
    $estHeight = 14 + 6 + (count($info['schema']) * 5) + 8;

    if ($pdf->NeedPageBreak(min($estHeight, 60))) {
        $pdf->AddPage();
    }

    $pdf->SectionHeading(
        $info['name'] . '  (' . number_format($info['rows']) . ' rows'
        . (!empty($info['pk']) ? '  |  PK: ' . implode(', ', $info['pk']) : '')
        . ')'
    );

    if (!empty($info['error'])) {
        $pdf->SetFont('Helvetica', 'I', 8);
        $pdf->SetTextColor(197, 48, 48);
        $pdf->Cell(0, 6, $pdf->encText('Error: ' . $info['error']), 0, 1);
        $pdf->SetTextColor(26, 32, 44);
        $pdf->Ln(4);
        continue;
    }

    if (empty($info['schema'])) {
        $pdf->SetFont('Helvetica', 'I', 8);
        $pdf->Cell(0, 6, 'No columns.', 0, 1);
        $pdf->Ln(4);
        continue;
    }

    $pdf->TableHeader($colHeaders, $colWidths);
    foreach ($info['schema'] as $ri => $col) {
        // Page break within a table if needed
        if ($pdf->NeedPageBreak(6)) {
            $pdf->AddPage();
            $pdf->SectionHeading($info['name'] . ' (continued)');
            $pdf->TableHeader($colHeaders, $colWidths);
        }
        $pdf->TableRow(
            [
                $col['name'],
                $col['type'],
                $col['nullable'] ? 'YES' : 'NO',
                $col['key'] ?? '',
                $col['default'] ?? '',
                $col['extra'] ?? '',
            ],
            $colWidths,
            ($ri % 2 === 1)
        );
    }
    $pdf->Ln(4);
}

// ── Output ──
$filename = preg_replace('/[^a-zA-Z0-9_\-.]/', '_', $dbLabel) . '_schema_' . date('Ymd') . '.pdf';
$pdf->Output('D', $filename);
exit;
